name = "chew-datasets"

# hashicorp/go-getter URLs support.
source_path = "file:${TESTGROUND_SRCDIR}/plans/chew-datasets"

[defaults]
builder = "docker:go"
runner = "local:docker"

# Builder strategies

[[builders]]
name="docker:go"
enabled = true
module_path = "github.com/ipfs/testground/plans/chew-datasets"
exec_pkg = "."
    [builders.params]
    go_version = { type = "string", desc = "the go lang version to be used", default: "1.13" }
    go_ipfs_version = { type = "string", desc = "the go-ipfs version to be tested", default: "0.4.22" }

[[builders]]
name="exec:go"
enabled = true
module_path = "github.com/ipfs/testground/plans/chew-datasets"
exec_pkg = "."
    [builders.params]

# Runner strategies

[[runners]]
name = "local:exec"
enabled = true
    [runners.params]
    cpu = { type = "string", desc = "the amount of CPU to be accessible to the runner" }
    ram = { type = "string", desc = "the amount of RAM to be accessible to the runner" }

[[runners]]
name = "local:docker"
enabled = true
    [runners.params]

[[runners]]
name = "cluster:nomad"
enabled = false
    [runners.params]


# Test cases

[[testcases]]
name = "ipfs-add-defaults"
instances = { min = 1, max = 1, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "ipfs-add-trickle-dag"
instances = { min = 1, max = 1, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "ipfs-add-dir-sharding"
instances = { min = 1, max = 1, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "ipfs-mfs"
instances = { min = 1, max = 1, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "ipfs-mfs-dir-sharding"
instances = { min = 1, max = 1, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "ipfs-url-store"
instances = { min = 1, max = 1, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "ipfs-file-store"
instances = { min = 1, max = 1, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }
