[metadata]
  name = "barrier"
  author = "adin"

[global]
  plan = "dht"
  case = "barrier"
  total_instances = 150
  builder = "docker:go"
  runner = "local:docker"

[[groups]]
  id = "balsam"
  [groups.instances]
    count = 75
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "1eeee542c2aa"
    [groups.run.test_params]
      timeout_secs = "600"

[[groups]]
  id = "balsam2"
  [groups.instances]
    count = 75
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "a2b53126d5ab"
    [groups.run.test_params]
      timeout_secs = "600"
